class Form():
    #gender = "id_gender1"
    f_name = "customer_firstname"
    l_name = "customer_lastname"
    password = "passwd"
    # days = "uniform-days"
    # months = "uniform-months"
    # years = "uniform-years"
    company = "company"
    address_1 = "address1"
    # address_2 = "address2"
    city = "city"
    state = "id_state"
    postcode = "postcode"
    country = "id_country"
    mobile = "phone_mobile"
    register = "//span[contains(.,'Register')]"
